= Zeiterfassung für Gruppe 09

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Darius |Felix |Huu An |Illia |Tim  |Tobias|Steve|Meeting
|1     |90     |90    |90     |90    |90   |90    |90   |00
|2     |350    |420   |480    |270   |570  |300   |270  |65
|3     |525    |525   |555    |750   |750  |495   |585  |50
|4     |420    |240   |285    |160   |510  |235   |310  |50
|5     |1445   |1335  |1060   |315   |1575 |645   |795  |45
|6     |180    |330   |180    |650   |540  |300   |480  |60
|7     |620    |555   |225    |180   |715  |225   |225  |55
|8     |1215   |570   |330    |260   |1370 |350   |390  |55
|9     |1355   |480   |420    |180   |960  |180   |380  |00
|10    |600    |540   |545    |520   |800  |545   |1245 |00
|11    |660    |660   |780    |720   |1930 |690   |660  |25
|12    |1050   |150   |1020   |220   |1540 |330   |720  |50
|INSG  |8510   |5895  |5470   |4315  |11350 |4385  |6150 |455
|AVG   |11,8   |8,2   |7,60   |6,00  |15,76 |6,09  |8,54 |0,63
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX)) Insgesamt: 46075

Arbeitsstunden pro Student: 42 075 / 7 = 109,70

Arbeitsstunden pro Woche pro Student: 9,14

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitszeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
